language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_script:
  - yarn
script: 
  - yarn generate
deploy:
  provider: script
  script: ./node_modules/.bin/push-dir --dir=dist --branch=gh-pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master